-- Editorial reports (Phase 2): a developmental-edit style report generated by
-- the worker from the full manuscript, the Story Bible and open issues.

alter table public.analysis_runs
  add column kind text not null default 'analysis' check (kind in ('analysis', 'report'));

alter table public.usage_events drop constraint usage_events_kind_check;
alter table public.usage_events
  add constraint usage_events_kind_check check (kind in ('analysis_words', 'question', 'free_tool', 'report'));

create table public.editorial_reports (
  id uuid primary key default gen_random_uuid(),
  book_id uuid not null references public.books (id) on delete cascade,
  owner_id uuid not null references auth.users (id) on delete cascade,
  run_id uuid not null references public.analysis_runs (id) on delete cascade,
  version_id uuid not null references public.manuscript_versions (id) on delete cascade,
  chapters_covered integer not null,
  data jsonb not null,
  created_at timestamptz not null default now()
);
create index editorial_reports_book on public.editorial_reports (book_id, created_at desc);

alter table public.editorial_reports enable row level security;
create policy "read own reports" on public.editorial_reports for select using (owner_id = auth.uid());
create policy "delete own reports" on public.editorial_reports for delete using (owner_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Admin metrics (service role only): activation funnel, revenue, AI cost, jobs.
-- ---------------------------------------------------------------------------

create function public.admin_metrics() returns jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'users', (select count(*) from profiles),
    'signups_7d', (select count(*) from profiles where created_at > now() - interval '7 days'),
    'signups_30d', (select count(*) from profiles where created_at > now() - interval '30 days'),
    'funnel', jsonb_build_object(
      'signed_up', (select count(*) from profiles),
      'onboarded', (select count(*) from profiles where onboarded_at is not null),
      'created_book', (select count(distinct owner_id) from books),
      'uploaded', (select count(distinct owner_id) from manuscript_versions),
      'analyzed', (select count(distinct owner_id) from analysis_runs where kind = 'analysis' and status = 'succeeded'),
      'asked', (select count(distinct owner_id) from questions),
      'reported', (select count(distinct owner_id) from editorial_reports),
      'paid', (select count(*) from subscriptions where plan <> 'free' and status in ('active', 'trialing', 'past_due'))
    ),
    'plans', (select coalesce(jsonb_object_agg(plan, n), '{}'::jsonb) from (
      select plan, count(*) as n from subscriptions where status in ('active', 'trialing', 'past_due') group by plan) p),
    'cancelling', (select count(*) from subscriptions where cancel_at_period_end),
    'ai_cost_30d', (select coalesce(jsonb_object_agg(kind, cost), '{}'::jsonb) from (
      select kind, round(sum(cost_usd)::numeric, 2) as cost from usage_events where created_at > now() - interval '30 days' group by kind) c),
    'free_tool_cost_30d', (select round(coalesce(sum(cost_usd), 0)::numeric, 2) from free_tool_runs where created_at > now() - interval '30 days'),
    'free_tool_runs_30d', (select count(*) from free_tool_runs where created_at > now() - interval '30 days'),
    'words_analyzed_30d', (select coalesce(sum(quantity), 0) from usage_events where kind = 'analysis_words' and created_at > now() - interval '30 days'),
    'jobs', jsonb_build_object(
      'queued', (select count(*) from analysis_runs where status = 'queued'),
      'running', (select count(*) from analysis_runs where status = 'running'),
      'succeeded_7d', (select count(*) from analysis_runs where status = 'succeeded' and created_at > now() - interval '7 days'),
      'failed_7d', (select count(*) from analysis_runs where status = 'failed' and created_at > now() - interval '7 days'),
      'avg_minutes_7d', (select round(avg(extract(epoch from finished_at - created_at) / 60)::numeric, 1) from analysis_runs
                          where status = 'succeeded' and created_at > now() - interval '7 days')
    ),
    'failed_runs', (select coalesce(jsonb_agg(f), '[]'::jsonb) from (
      select r.id, r.kind, r.error, r.attempts, r.created_at, b.title from analysis_runs r join books b on b.id = r.book_id
       where r.status = 'failed' order by r.created_at desc limit 20) f),
    'recent_users', (select coalesce(jsonb_agg(u), '[]'::jsonb) from (
      select p.display_name, p.writing_type, p.writing_stage, p.created_at, s.plan,
             (select count(*) from books b where b.owner_id = p.id) as books
        from profiles p left join subscriptions s on s.owner_id = p.id
       order by p.created_at desc limit 20) u)
  );
$$;
revoke execute on function public.admin_metrics() from public, anon, authenticated;
